# Thanks to https://github.com/ading2210/badrecovery for the orginal badrecovery workflow file
on: workflow_dispatch
name: build

jobs:
  build:
    permissions:
      contents: write
    
    strategy: 
      matrix:
        board: [nissa]

    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 32768
          swap-size-mb: 64
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: download repo
        uses: actions/checkout@v4
      
      - name: run build
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler pv
          sudo apt-get install -y pv
          sudo pip3 install protobuf six --break-system-packages
          sudo QUIET=1 bash buildfull_badsh1mmer.sh "${{ matrix.board }}"
          
      - name: upload disk image
        uses: actions/upload-artifact@v4
        with:
          name: badsh1mmer_${{ matrix.board }}
          path: badsh1mmer_*.bin
          compression-level: 7

      - name: create release
        uses: ading2210/gh-large-releases@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: badsh1mmer-*.bin
          make_latest: true
